name: cd
on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: connect to droplet
        run: |
          ssh root@159.89.179.110
          yes
          2025-Papaya-Pals
          ls
  