name: cd
on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: 159.89.179.110
          username: root
          password: 2025-Papaya-Pals
          script: | 
            cd 5-final-papaya-pals 
            ls 
      - name: Execute remote ALL SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: 159.89.179.110
          username: root
          password: 2025-Papaya-Pals
          script: | 
            cd 5-final-papaya-pals
            ls
            docker-compose down 
            git pull origin main 
            docker-compose up --force-recreate --build -d 