name: lint-free
on: [push, pull_request]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          cd web-app
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv lock
          pipenv install pylint
          pipenv sync --dev --python $(which python)
          pipenv shell --fancy --python $(which python)
      - name: Lint with pylint
        run: |
          cd web-app
          pipenv run pylint *.py
          pipenv run pylint **/*.py
          pipenv run pylint **/**/*.py
      - name: Format with black
        run: |
          cd web-app
          pipenv run black --diff --check .